openapi: 3.0.1
info:
  title: Bookstore API
  description: API for managing a collection of books.
  version: 1.0.0

components:
  schemas:
    Book:
      type: object
      required:
        - id
        - title
        - author
        - publishedDate
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "The Great Gatsby"
        author:
          type: string
          example: "F. Scott Fitzgerald"
        publishedDate:
          type: string
          format: date
          example: "1925-04-10"
