version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management # Version with the management plugin enabled
    container_name: my_rabbitmq
    ports:
      - "5672:5672"         # Custom port mapping for RabbitMQ client connections
      - "15672:15672"       # Custom port mapping for the management console
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persisted volume for RabbitMQ data
    environment:
      RABBITMQ_DEFAULT_USER: user        # Default username
      RABBITMQ_DEFAULT_PASS: password    # Default password
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:                         # Named volume to persist data
    driver: local

networks:
  rabbitmq_network:                      # Custom network for RabbitMQ
    driver: bridge
